# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.4/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/warredevriese/Developer/c/cub3d

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/warredevriese/Developer/c/cub3d

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/warredevriese/Developer/c/cub3d/CMakeFiles /Users/warredevriese/Developer/c/cub3d//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/warredevriese/Developer/c/cub3d/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my_app

# Build rule for target.
my_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 my_app
.PHONY : my_app

# fast build rule for target.
my_app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/build
.PHONY : my_app/fast

#=============================================================================
# Target rules for targets named re

# Build rule for target.
re: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 re
.PHONY : re

# fast build rule for target.
re/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/re.dir/build.make CMakeFiles/re.dir/build
.PHONY : re/fast

#=============================================================================
# Target rules for targets named fclean

# Build rule for target.
fclean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fclean
.PHONY : fclean

# fast build rule for target.
fclean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fclean.dir/build.make CMakeFiles/fclean.dir/build
.PHONY : fclean/fast

src/image_utils.o: src/image_utils.c.o
.PHONY : src/image_utils.o

# target to build an object file
src/image_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/image_utils.c.o
.PHONY : src/image_utils.c.o

src/image_utils.i: src/image_utils.c.i
.PHONY : src/image_utils.i

# target to preprocess a source file
src/image_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/image_utils.c.i
.PHONY : src/image_utils.c.i

src/image_utils.s: src/image_utils.c.s
.PHONY : src/image_utils.s

# target to generate assembly for a file
src/image_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/image_utils.c.s
.PHONY : src/image_utils.c.s

src/images.o: src/images.c.o
.PHONY : src/images.o

# target to build an object file
src/images.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/images.c.o
.PHONY : src/images.c.o

src/images.i: src/images.c.i
.PHONY : src/images.i

# target to preprocess a source file
src/images.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/images.c.i
.PHONY : src/images.c.i

src/images.s: src/images.c.s
.PHONY : src/images.s

# target to generate assembly for a file
src/images.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/images.c.s
.PHONY : src/images.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/main.c.s
.PHONY : src/main.c.s

src/map_content_check.o: src/map_content_check.c.o
.PHONY : src/map_content_check.o

# target to build an object file
src/map_content_check.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/map_content_check.c.o
.PHONY : src/map_content_check.c.o

src/map_content_check.i: src/map_content_check.c.i
.PHONY : src/map_content_check.i

# target to preprocess a source file
src/map_content_check.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/map_content_check.c.i
.PHONY : src/map_content_check.c.i

src/map_content_check.s: src/map_content_check.c.s
.PHONY : src/map_content_check.s

# target to generate assembly for a file
src/map_content_check.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/map_content_check.c.s
.PHONY : src/map_content_check.c.s

src/parsing.o: src/parsing.c.o
.PHONY : src/parsing.o

# target to build an object file
src/parsing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/parsing.c.o
.PHONY : src/parsing.c.o

src/parsing.i: src/parsing.c.i
.PHONY : src/parsing.i

# target to preprocess a source file
src/parsing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/parsing.c.i
.PHONY : src/parsing.c.i

src/parsing.s: src/parsing.c.s
.PHONY : src/parsing.s

# target to generate assembly for a file
src/parsing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/parsing.c.s
.PHONY : src/parsing.c.s

src/player_check.o: src/player_check.c.o
.PHONY : src/player_check.o

# target to build an object file
src/player_check.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/player_check.c.o
.PHONY : src/player_check.c.o

src/player_check.i: src/player_check.c.i
.PHONY : src/player_check.i

# target to preprocess a source file
src/player_check.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/player_check.c.i
.PHONY : src/player_check.c.i

src/player_check.s: src/player_check.c.s
.PHONY : src/player_check.s

# target to generate assembly for a file
src/player_check.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/player_check.c.s
.PHONY : src/player_check.c.s

src/player_init.o: src/player_init.c.o
.PHONY : src/player_init.o

# target to build an object file
src/player_init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/player_init.c.o
.PHONY : src/player_init.c.o

src/player_init.i: src/player_init.c.i
.PHONY : src/player_init.i

# target to preprocess a source file
src/player_init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/player_init.c.i
.PHONY : src/player_init.c.i

src/player_init.s: src/player_init.c.s
.PHONY : src/player_init.s

# target to generate assembly for a file
src/player_init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/player_init.c.s
.PHONY : src/player_init.c.s

src/player_movements.o: src/player_movements.c.o
.PHONY : src/player_movements.o

# target to build an object file
src/player_movements.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/player_movements.c.o
.PHONY : src/player_movements.c.o

src/player_movements.i: src/player_movements.c.i
.PHONY : src/player_movements.i

# target to preprocess a source file
src/player_movements.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/player_movements.c.i
.PHONY : src/player_movements.c.i

src/player_movements.s: src/player_movements.c.s
.PHONY : src/player_movements.s

# target to generate assembly for a file
src/player_movements.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/player_movements.c.s
.PHONY : src/player_movements.c.s

src/raycaster_drawing.o: src/raycaster_drawing.c.o
.PHONY : src/raycaster_drawing.o

# target to build an object file
src/raycaster_drawing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/raycaster_drawing.c.o
.PHONY : src/raycaster_drawing.c.o

src/raycaster_drawing.i: src/raycaster_drawing.c.i
.PHONY : src/raycaster_drawing.i

# target to preprocess a source file
src/raycaster_drawing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/raycaster_drawing.c.i
.PHONY : src/raycaster_drawing.c.i

src/raycaster_drawing.s: src/raycaster_drawing.c.s
.PHONY : src/raycaster_drawing.s

# target to generate assembly for a file
src/raycaster_drawing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/raycaster_drawing.c.s
.PHONY : src/raycaster_drawing.c.s

src/raycaster_prep.o: src/raycaster_prep.c.o
.PHONY : src/raycaster_prep.o

# target to build an object file
src/raycaster_prep.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/raycaster_prep.c.o
.PHONY : src/raycaster_prep.c.o

src/raycaster_prep.i: src/raycaster_prep.c.i
.PHONY : src/raycaster_prep.i

# target to preprocess a source file
src/raycaster_prep.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/raycaster_prep.c.i
.PHONY : src/raycaster_prep.c.i

src/raycaster_prep.s: src/raycaster_prep.c.s
.PHONY : src/raycaster_prep.s

# target to generate assembly for a file
src/raycaster_prep.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/raycaster_prep.c.s
.PHONY : src/raycaster_prep.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fclean"
	@echo "... re"
	@echo "... my_app"
	@echo "... src/image_utils.o"
	@echo "... src/image_utils.i"
	@echo "... src/image_utils.s"
	@echo "... src/images.o"
	@echo "... src/images.i"
	@echo "... src/images.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/map_content_check.o"
	@echo "... src/map_content_check.i"
	@echo "... src/map_content_check.s"
	@echo "... src/parsing.o"
	@echo "... src/parsing.i"
	@echo "... src/parsing.s"
	@echo "... src/player_check.o"
	@echo "... src/player_check.i"
	@echo "... src/player_check.s"
	@echo "... src/player_init.o"
	@echo "... src/player_init.i"
	@echo "... src/player_init.s"
	@echo "... src/player_movements.o"
	@echo "... src/player_movements.i"
	@echo "... src/player_movements.s"
	@echo "... src/raycaster_drawing.o"
	@echo "... src/raycaster_drawing.i"
	@echo "... src/raycaster_drawing.s"
	@echo "... src/raycaster_prep.o"
	@echo "... src/raycaster_prep.i"
	@echo "... src/raycaster_prep.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

